export const countries = [
  'Afghanistan',
  'Afrique du Sud',
  'Albanie',
  'Algérie',
  'Allemagne',
  'Andorre',
  'Angola',
  'Anguilla',
  'Antarctique',
  'Antigua-et-Barbuda',
  'Antilles néerlandaises',
  'Apatride',
  'Arabie Saoudite',
  'Argentine',
  'Arménie',
  'Aruba',
  'Australie',
  'Autorité nation.palestin.',
  'Autres Îles du Pacifique',
  'Autriche',
  'Azerbaïdjan',
  'Bahamas',
  'Bahreïn',
  'Bangladesh',
  'Barbade',
  'Bélarus',
  'Belgique',
  'Belize',
  'Bénin',
  'Bermudes',
  'Bhoutan',
  'Bolivie',
  'Bonaire, Saint-Eustache et Saba',
  'Bosnie-Herzégovine',
  'Botswana',
  'Brésil',
  'Brunéi',
  'Bulgarie',
  'Burkina Faso',
  'Burundi',
  'Cambodge',
  'Cameroun',
  'Canada',
  'Cap-vert',
  'Chili',
  'Chine',
  'Chypre',
  'Colombie',
  'Communauté des États indépendants (CEI)',
  'Comores',
  'Congo, répub. démocrat.',
  'Congo, république du',
  'Cook, Îles',
  'Corée du Nord',
  'Corée du Sud',
  'Costa Rica',
  "Côte d'Ivoire",
  'Croatie',
  'Cuba',
  'Curaçao',
  'Danemark',
  'Djibouti',
  'Dominique',
  'Égypte',
  'El Salvador',
  'Émirats Arabes Unis',
  'Équateur',
  'Érythrée',
  'Espagne',
  'Estonie',
  'États-Unis',
  'Éthiopie',
  'Fidji',
  'Finlande',
  'France',
  'Gabon',
  'Gambie',
  'Géorgie',
  'Géorgie du Sud et les Îles Sandwich du Sud',
  'Ghana',
  'Gibraltar',
  'Grèce',
  'Grenade',
  'Groenland',
  'Guadeloupe',
  'Guam (Guaham)',
  'Guatemala',
  'Guernesey',
  'Guinée',
  'Guinée Équatoriale',
  'Guinée-Bissau',
  'Guyane',
  'Guyane Française',
  'Haïti',
  'Honduras',
  'Hong-Kong',
  'Hongrie',
  'Île Bouvet',
  'Île Christmas',
  'Île de Man',
  'Île Heard-Îles Macdonald',
  'Île Norfolk',
  'Îles Åland',
  'Îles Caïmans',
  'Îles Channel',
  'Îles Cocos (Keeling)',
  'Îles Falkland',
  'Îles Féroé',
  'Îles Mariannes du Nord',
  'Îles Marshall',
  'Îles Mayotte',
  'Îles Mineures Éloignées des États-Unis',
  'Îles Salomon',
  'Îles Turks et Caïcos',
  'Îles Vierges Britanniques',
  'Îles Vierges des États-Unis',
  'Îles Wallis et Futuna',
  'Inde',
  'Indonésie',
  'Iran',
  'Iraq',
  'Irlande',
  'Islande',
  'Israël',
  'Italie',
  'Jamaïque',
  'Japon',
  'Jersey',
  'Jordanie',
  'Kazakhstan',
  'Kenya',
  'Kirghizistan',
  'Kiribati',
  'Kosovo',
  'Koweït',
  'Lao, répub. démocrat.',
  'Lesotho',
  'Lettonie',
  'Liban',
  'Libéria',
  'Libye ',
  'Liechtenstein',
  'Lituanie',
  'Luxembourg',
  'Macao',
  'Macédoine',
  'Madagascar',
  'Malaisie',
  'Malawi',
  'Maldives',
  'Mali',
  'Malte',
  'Maroc',
  'Martinique',
  'Maurice',
  'Mauritanie',
  'Mexique',
  'Micronésie',
  'Moldova',
  'Monaco',
  'Mongolie',
  'Monténégro ',
  'Montserrat',
  'Mozambique',
  'Myanmar',
  'Namibie',
  'Nauru',
  'Népal',
  'Nicaragua',
  'Niger',
  'Nigéria',
  'Niue (Nioué)',
  'Norvège',
  'Nouvelle-Calédonie',
  'Nouvelle-Zélande',
  'Oman',
  'Ouganda',
  'Ouzbékistan',
  'Pakistan',
  'Palaos',
  'Panama',
  'Papouasie-Nouvelle-Guinée',
  'Paraguay',
  'Pays-Bas',
  'Pérou',
  'Philippines',
  'Pitcairn',
  'Pologne',
  'Polynésie Française',
  'Porto Rico',
  'Portugal',
  'Qatar',
  'République Centrafricaine',
  'République de Serbie',
  'République démocratique allemande',
  'République Dominicaine',
  'République slovaque',
  'République tchèque',
  'Réunion',
  'Roumanie',
  'Royaume-Uni',
  'Russie',
  'Rwanda',
  'Sahara Occidental',
  'Saint-Barthélemy ',
  'Saint-Kitts-et-Nevis',
  'Saint-Marin',
  'Saint-Martin (française)',
  'Saint-Martin (Partie Néerlandaise) ',
  'Saint-Pierre-et-Miquelon',
  'Saint-Vincent-et-les Grenadines',
  'Sainte-Hélène',
  'Sainte-Lucie',
  'Samoa',
  'Samoa Américaines',
  'Sao Tomé-et-Principe',
  'Sénégal',
  'Serbie-et-Monténégro',
  'Seychelles',
  'Sierra Leone',
  'Sikkim',
  'Singapour',
  'Slovénie',
  'Somalie',
  'Soudan',
  'Soudan du Sud',
  'Sri Lanka',
  'Suède',
  'Suisse',
  'Suriname',
  'Svalbard et Île Jan Mayen',
  'Swaziland',
  'Syrie',
  'Tadjikistan',
  'Taïwan',
  'Tanzanie',
  'Tchad',
  'Tchécoslovaquie',
  'Terres Australes Françaises',
  "Territoire Britannique de l'Océan Indien",
  "Territoires Espagnols de l'Afrique du nord",
  'Thaïlande',
  'Timor-Leste',
  'Togo',
  'Tokélau',
  'Tonga',
  'Trinité-et-Tobago',
  'Tunisie',
  'Turkménistan',
  'Turquie',
  'Tuvalu',
  'U.R.S.S.',
  'Ukraine',
  'Uruguay',
  'Vanuatu',
  'Vatican',
  'Venezuela',
  'Viet Nam',
  'Yémen',
  'Yémen du Sud',
  'Zambie',
  'Zimbabwe',
];
